---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev-mysql
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dev-mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql
    version: 1.6.2
  values:
    ssl:
      enabled: false
  valuesFrom:
  - secretKeyRef:
      name: mysql-auth
      namespace: dev
