---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stg-go-team
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: stg-go-team
  chart:
    git: git@github.com:cbellee/flux-helm-cd
    path: charts/go-team
    ref: master
  values:
    image: 
      repository: belstarr/go-team
      tag: stg-0.1.0.2972
    service:
      name: dev-go-team-mysql.dev
    dbHostName: stg-go-team-mysql
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: go-team.kainiindustries.net