---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stg-mysql
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    #filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: stg-mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql
    version: 1.6.2
  values:
    ssl:
    - enabled: false
  valuesFrom:
  - secretKeyRef:
      name: mysql-auth
      namespace: stg
